# Generated by Django 3.0.6 on 2021-06-26 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisheddate',
            field=models.DateField(default=datetime.date(2021, 6, 26)),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='ratingscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='reviewscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
