# Generated by Django 3.0.6 on 2021-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0002_auto_20210626_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisheddate',
            field=models.CharField(max_length=20),
        ),
    ]
