# Generated by Django 3.0.6 on 2021-07-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0005_dailyuserreadinggoal_userreadinggoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyuserreadinggoal',
            old_name='minutes',
            new_name='completedminutes',
        ),
    ]
