# Generated by Django 3.0.6 on 2021-07-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0006_auto_20210711_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserreadinggoal',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EBookReadingApp.UserReadingGoal'),
        ),
    ]
