# Generated by Django 3.0.6 on 2021-07-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0007_dailyuserreadinggoal_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreadinggoal',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EBookReadingApp.UserReadingGoal'),
        ),
    ]
