# Generated by Django 3.0.6 on 2021-07-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0008_auto_20210711_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreadinggoal',
            name='completedminutes',
            field=models.FloatField(),
        ),
    ]
