# Generated by Django 3.0.6 on 2021-07-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0010_auto_20210713_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
