# Generated by Django 3.0.6 on 2021-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0011_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreadinggoal',
            name='date',
            field=models.DateField(),
        ),
    ]
