# Generated by Django 3.0.6 on 2021-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0012_auto_20210715_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreadinggoal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
