# Generated by Django 3.0.6 on 2021-07-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0014_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreadinggoal',
            name='date',
            field=models.DateField(),
        ),
    ]
