# Generated by Django 3.0.6 on 2021-07-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBookReadingApp', '0015_auto_20210727_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyuserreadinggoal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
